name: my_eyes_mobile
description: "MY EYES - Pakistan's First Prescription Based Eyewear Store Mobile App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
